name: API tests from Postman cloud using Postman CLI

on: workflow_dispatch

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "21196236-cd1e8df9-da2b-4583-80bf-17313fbb368b" -e "21196236-797229e6-ff09-4412-9dc4-c9307fdf23e0"
