# This is a basic workflow to help you get started with Actions

name: Automated API tests using Postman CLI

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Install Newman CLI
        run: npm install -g newman
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: newman run "Postman Collections/GAD-Postman_test_collection.json" --environment "Postman Collections/Test (render.com).postman_environment.json"
