name: Automated API tests using Newman
# Controls when the workflow will run
on: workflow_dispatch

# A workflow run
jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - name: Install Newman CLI
        run: npm install -g newman
      - name: Install Newman HTML reporter
        run: npm install -g newman-reporter-htmlextra
      - name: Run API tests
        run: newman run "Postman Collections/GAD-Postman_test_collection.json" --environment "Postman Collections/Test (render.com).postman_environment.json" -r cli,htmlextra
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report
          path: newman
