name: Automated API tests using Postman CLI

on: workflow_dispatch

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Run API tests
        run: |
          postman collection run "Postman Collections/GAD-Postman_test_collection.json" -e "Postman Collections/Test (render.com).postman_environment.json"
